// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { Application } from "@hotwired/stimulus"
// This import is correct for the stimulus-loading.js file you have
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"

const application = Application.start()

// This line automatically loads and registers all your *_controller.js files
// under the 'controllers' directory, as mapped in config/importmap.rb
eagerLoadControllersFrom("controllers", application)